### |-----------------| REGISTRO |-----------------|
POST https://ll--2--ll.herokuapp.com/register
Content-Type:  application/json

{
    "username": "user1",
    "password": "oasuet10"
}
### |-----------------| AUTORIZAÇÂO |-----------------|
# POST https://ll--2--ll.herokuapp.com/login
POST https://ll--2--ll.herokuapp.com/auth
Content-Type:  application/json

{
    "username": "user1",
    "password": "oasuet10"
}

### |-----------------| CRIAR UM ITEM |-----------------|
POST https://ll--2--ll.herokuapp.com/item/pao
Content-Type:  application/json

{
    "price": 2.9,
    "store_id": 1
}

### |-----------------| DELETAR UM ITEM |-----------------|
DELETE   https://ll--2--ll.herokuapp.com/item/abacaxi  

### |-----------------| CRIAR/MODIFICAR UM ITEM |-----------------|
PUT  https://ll--2--ll.herokuapp.com/item/abacaxi
Content-Type:  application/json

{
    "price": 420.69,
    "store_id": 1,
    "nada": "Isso vai ser ignorado pelo parser"
}

###  |-----------------| PEGAR UM ITEM |-----------------|
GET  https://ll--2--ll.herokuapp.com/item/test
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDA3Mzc0OTIsImlhdCI6MTYwMDczNzE5MiwibmJmIjoxNjAwNzM3MTkyLCJpZGVudGl0eSI6MX0.m155b0QWYKfZMwpx8VzMA7zF3Y2AS17yLY9mJwD8OlY

### |-----------------| LISTA DE ITEMS |-----------------|
GET  https://ll--2--ll.herokuapp.com/items

###  |-----------------| CRIAR UMA STORE |-----------------|
POST  https://ll--2--ll.herokuapp.com/store/test
Content-Type:  application/json

{
    "name": "test"
}

###  |-----------------| PEGAR UMA STORE |-----------------|
GET  https://ll--2--ll.herokuapp.com/store/test

### |-----------------| LISTA DE STORES |-----------------|
GET  https://ll--2--ll.herokuapp.com/stores